#%RAML 1.0
title: Test raml2html
baseUri: example.com
description: Demonstrate the error in generating html from a RAML 1.0 file
version: 0.1
mediaType: application/json
types:
  test:
    displayName: Test
    type: object
    properties:
      message: string
    examples:
      foo:
        {
          "message": "foo"
        }
      bar:
        {
          "message": "bar"
        }
/foo:
  get:
    responses:
      200:
        body:
          application/json:
            examples:
              foo:
                {
                  "joe": "bob"
                }
